### ISSUE TITLE
Disable the border under iOS

### ISSUE THREAD

**Issue by Genfood** [dotMorten/XamarinFormsControls#11]
Is there a way to disable the textbox border under iOS? So it matches the usual layout in a ViewCell (TextCell).

**Comment by dotMorten** [comment]
Currently not. Could you post a screen shot of what it looks like and what you'd like it to look like.
And do you think this needs to be settable, or should what you suggest be the default?

**Comment by Genfood** [comment]
I mean to set the UiLabel BorderStyle to none.

**Comment by dotMorten** [comment]
I've changed the style so there's only a border at the bottom, which seems to match the layout used in many of the default iOS apps, and also matches Android as well.

**Comment by MysterDru** [comment]
@dotMorten can this be configurable? I upgraded my app to the latest version today and now my autosuggestbox has the bottom border. All of the input fields in our app are the standard, default, rounded border styles for iOS.

It would be nice to have the ability to enable or disable this "custom" style of the bottom only border on iOS. I need to either change all the inputs in my app to match this new style, or stay on an earlier version of this library. 

Neither one of those are an ideal solution.

**Comment by dotMorten** [comment]
@MysterDru It's hard to please everyone :-)

I'd suggest you submit a feature request for controlling all the sides of the border - I'm not entirely sure how to handle this across all platforms or if there's a common pattern for this on other controls already that I can copy.

**Comment by dotMorten** [comment]
...also there's a 3rd option: Fork the code and make a local fix

**Comment by MysterDru** [comment]
@dotMorten perfectly understandable, I know exactly what you mean. Another option would be to let the renderers be public rather than internal. I was going to try to make a custom renderer to customize it without needing to include the full source in my project, but the renderers are currently internal.

I'll create a issue as a request.

**Comment by dotMorten** [comment]
Public renderers is an interesting approach too. That does seem to match the pattern Xamarin.Forms are using in their libraries. I'd be interested to know how you plan on utilizing it in that case.
