### ISSUE TITLE
Control color is not the default. 

### ISSUE THREAD

**Issue by Welchen** [dotMorten/XamarinFormsControls#13]
The control color on Android is coming up white for me and not the default color. I see means to change the BackgroundColor but not the color of the control itself.

**Comment by dotMorten** [comment]
This appears to be a duplicate of #2,
Settings for TextColor was recently added to the source, but a new nuget package hasn't been published. Are you building from source?

**Comment by Welchen** [comment]
Yes I am building from the source. I have the TextColor change from the source but my issue is with the control color or the theme of the control.

**Comment by LeoJHarris** [comment]
Really like to see some more properties on the control exposed, particularly around colors and fonts... thanks for the plugin, really nice otherwise

**Comment by dotMorten** [comment]
@leoJHarris please log a separate issue with specifics. This issue here is essentially completed.
Also, I do take pull requests, and would really appreciate the community to pitch in for areas that goes beyond what I needed to work

**Comment by LeoJHarris** [comment]
@dotMorten I pulled your project and added in properties I need myself ... PlaceHolderTextColor and for android I added in BackgroundTintList

**Comment by dotMorten** [comment]
@Welchen Could you try v0.2.0 and see if this still happens? I've improved how the control gets created so it _should_ be better at picking up the system style

**Comment by dotMorten** [comment]
Closing due to no response. Please reopen if you still see an issue
