### ISSUE TITLE
.NET Standard 1.x Support

### ISSUE THREAD

**Issue by prof79** [dotMorten/XamarinFormsControls#14]
### Description
Hi there, congratulations on your efforts!

You certainly had your reasons to only support .NET Standard 2.0 and Xamarin Forms 3.x - but I require support for Windows 10 Mobile thus having the limits to be .NET Standard <= 1.4 and Xamarin Forms 2.5.*.

Thus, just as an information, I've created my own branch prof79-netstandard1x in a fork. I couldn't test iOS but works nicely on UWP, UWP Mobile and Android. Might be helpful for those who still require XF 2.5.x or need W10M support.

Cheers!

### Steps to Reproduce

1. Add package to downlevel UWP project (< 16299 eg. 10586)
2. 
3. 

### Expected Behavior
Works

### Actual Behavior
Doesn't work

### Basic Information

- Version with issue:
- Last known good version: -
- IDE: Visual Studio Community 2017 15.8.1
- Platform Target Frameworks: 
  - iOS:  
  - Android: 7.1  
  - UWP: 10586   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices: Lumia 950

**Comment by dotMorten** [comment]
Awesome! I'm a big WP fan myself but that ship has sadly sailed and thus I didn't want to add to the overhead of supporting it. There's been a lot of changes to 3.x (including breaking ones) and Xamarin technical doesn't support older versions so I made the call to not support a lot of older versions.

**Comment by wtheronjones** [comment]
I see this is closed, but I would need a version that supports netstandard 1.x because I am also using Visual Studio for Mac which only seems to support PCLs and netstandard1-> 1.5. Just fyi.

**Comment by dotMorten** [comment]
That doesn't sound right to me, but I have no plans to downgrade at this point. If this is truly an issue in vs4mac make sure you log an issue with the VS team
/Cc @unnir

**Comment by wtheronjones** [comment]
I have a Xamarin Forms project that started as a PCL and was converted to NetStandard 1.1.  In vs4mac I can only select netstandard, up to 1.5.
Interestingly enough, I just created a new proj and using the project template for Xamarin Forms library in vs4mac and it defaulted to targeting netstandard2.0 .   Probably easy enough for me to convert my project.

**Comment by prof79** [comment]
@wtheronjones I'm having a bit of a Xamarin hiatus right now due to some other stuff but if it works for you be my guest and clone/use my pull request version which should be compatible:

https://github.com/prof79/XamarinFormsControls/tree/prof79-netstandard1x
