### ISSUE TITLE
Text Color not usable

### ISSUE THREAD

**Issue by concedev** [dotMorten/XamarinFormsControls#20]
### Steps to Reproduce

1.  property textcolor not work on android 
2. 
3. 

### Basic Information

- Version with issue: 0.1.0 
- Last known good version:
- IDE: Visual Studio 2017
- Platform Target Frameworks: 
  - iOS:  
  - Android:  4.3
  - UWP:  
- Android Support Library Version: 
- Nuget Packages: https://www.nuget.org/packages/dotMorten.Xamarin.Forms.AutoSuggestBox/
- Affected Devices: All devices Android

**Comment by dotMorten** [comment]
I wasn't able to reproduce this on Android. Setting TextColor and BackgroundColor works for me:

```xml
<dm:AutoSuggestBox TextColor="Green" BackgroundColor="Red" />
```
![image](https://user-images.githubusercontent.com/1378165/51064243-9682e200-15b3-11e9-8b6d-a83bcd91ec8d.png)
