### ISSUE TITLE
IsSuggestionListOpen is not working

### ISSUE THREAD

**Issue by Ankhiya** [dotMorten/XamarinFormsControls#21]
### Description
I wanted to show drop down before user type anything. So I tried to call IsSuggestionListOpen  on autosuggestbox but is not showing dropdown at all.

**Comment by dotMorten** [comment]
Suggest box should now auto-open on focus if the itemssource has items (this was a bug and was previous only working on UWP), so this code should no longer be necessary (as of v0.6.0)
