### ISSUE TITLE
Android: crash in AutoSuggestBoxRenderer.OnElementChanged

### ISSUE THREAD

**Issue by mfeingol** [dotMorten/XamarinFormsControls#23]
### Description

Seeing occasional reports of this on Android. I'm using the autosuggest box in my app embedded in a settings page. I haven't seen this crash personally.

### Steps to Reproduce

Unknown.

### Expected Behavior

No crashes.

### Actual Behavior

```
AutoSuggestBoxRenderer.OnElementChanged (Xamarin.Forms.Platform.Android.ElementChangedEventArgs`1[TElement] e)
Java.Lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.

JniEnvironment+InstanceMethods.CallNonvirtualVoidMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args)
JniPeerMembers+JniInstanceMethods.InvokeVirtualVoidMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters)
ViewGroup.AddView (Android.Views.View child, System.Int32 index)
ViewRenderer`2[TView,TNativeView].SetNativeControl (TNativeView control, Android.Views.ViewGroup container)
ViewRenderer`2[TView,TNativeView].SetNativeControl (TNativeView control)
AutoSuggestBoxRenderer.OnElementChanged (Xamarin.Forms.Platform.Android.ElementChangedEventArgs`1[TElement] e)
VisualElementRenderer`1[TElement].SetElement (TElement element)
```

### Basic Information

- Version with issue: 0.1.0
- Last known good version: N/A
- IDE:
- Platform Target Frameworks: 
  - Android: 9.0
- Android Support Library Version: 27.0.2.1

### Screenshots

N/A

### Reproduction Link

N/A

**Comment by dotMorten** [comment]
I've made some changes to how views are created and added, which matches how xamarin.forms' own controls does it. Could you try the latest code in the repo and see if it still reproduces?

**Comment by mfeingol** [comment]
Thanks for the update. Unfortunately I've already removed this control from my production app, and I was only seeing this from crash reports in production. But if you do publish a new Nuget version, I may try again at some point in time.

**Comment by dotMorten** [comment]
Thanks. And sorry for the slow response. I hope to have an updated version out soon. If the issue comes back then, feel free to reopen.
