### ISSUE TITLE
Keyboard suggestions

### ISSUE THREAD

**Issue by saimel** [dotMorten/XamarinFormsControls#3]
Great component!! I'm trying it up and looks really good, however there is a small detail that once fixed, this component will be best. I'm talking about Keyboard suggestions. Xamarin Forms Entry has property IsTextPredictionEnabled, I think it should be added to AutoSuggestBox too, otherwise completion list can get overlapped with keyboard suggestions.

Thanks for this awesome development !

**Comment by dotMorten** [comment]
@saimel Thank you for trying it out and providing feedback. Would you think the default should be off?

**Comment by dotMorten** [comment]
Actually digging around I can do this for Android and iOS, but I can't do it for UWP as it doesn't have an option to turn on/off, so I'm thinking it would be better just to turn it off on all platforms, rather than make it a setting. Sounds good?

**Comment by saimel** [comment]
Sounds great!!

**Comment by dotMorten** [comment]
Cool. I'm hoping to push this fix tonight. Seems simple enough.
If you can't wait, in NativeAutoSuggestBox.Android.cs change the InputType setter in the constructor:
`InputType = Android.Text.InputTypes.ClassText | Android.Text.InputTypes.TextFlagNoSuggestions;`.
In the iOS one, set `AutocorrectionType = UITextAutocorrectionType.No`, where the inputText instance is created.

I haven't tested this yet, but this seems to be what the EntryRenderer is doing in Xamarin.Forms.

**Comment by dotMorten** [comment]
...or feel free to submit a PR if you have time to try it out and test it :-)

**Comment by saimel** [comment]
Unfortunately I've no time for this, we are in some kind of rush with a release, I think I can wait for you with no problem. Thanks very much for the feedback.
