### ISSUE TITLE
Can't move focus away from AutoSuggestBox after QuerySubmitted

### ISSUE THREAD

**Issue by Lelelo1** [dotMorten/XamarinFormsControls#32]
### Description:
When submitting, the AutoSuggestBox should be unselected

### Steps to Reproduce

1. Create a AutoSuggestBox like in the documentation
2. Create a Label - something to move focus to
3. In QuerySubmitted event handler: Unfocus the Page, move focus to Label

### Expected Behavior: 
When QuerySubmitted the keyboard in iOS should dissapear, and the AutoSuggestBox to be unselected

### Actual Behaviour
The Keyboard remains open. (The user has to press somewhere to unselect the AutoSuggestBox)

### Basic Information

- Version with issue: 5.0
- Last known good version: 
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Screenshots
![autosuggestboxfocus](https://user-images.githubusercontent.com/42244983/51438633-f7df3b00-1cae-11e9-9c26-187c2dabd582.png)

**Comment by dotMorten** [comment]
Thanks. This is good feedback. I'll look at what the entry renderer is doing wrt focus and see if I can't duplicate that.

**Comment by dotMorten** [comment]
Fixed in v0.6.0
