### ISSUE TITLE
Allow Renderers to be extended

### ISSUE THREAD

**Issue by MysterDru** [dotMorten/XamarinFormsControls#33]
### Description
This is a new issue created from another discussion on issue #11. 

I upgraded to the newest version (0.6.0) of this library earlier today to gain access to the focus events that were added. In doing so, I discovered that the default iOS round borders for inputs were replaced with a single bottom border. 

In my app in particular, this causes a problem due to all other Xamarin.Forms entries relying on the default out-of-the-box styling. 

I attempted to extend the renderers for the autosuggestbox so I could get the styles to match the rest of my app, but it looks like renderers are currently internal. 

Are there any issues/concerns with making the renderers public so developers could customize the styling of the control without needing to fork or include the source manually?

**Comment by dotMorten** [comment]
@MysterDru I'm open to this idea, but any chance you could post an example how making the renderers public solves this problem? I'd like to use it to better understand the solution to your problem if they were public, so I can expose them "right" (I haven't personally messed with overriding the default renderers before).

**Comment by dotMorten** [comment]
Closing as this was added in 0.7 with a sample showing how
