### ISSUE TITLE
Choose in which direction the suggestion box opens

### ISSUE THREAD

**Issue by gabrielbunselmeyer** [dotMorten/XamarinFormsControls#37]
### Description
Idea's quite simple, really: have a way to set in which way (up/down) the suggestion box opens. In Android this doesn't seem to be a problem as the native view (?) detects the end of the screen and adjusts appropriately. However, in iOS, if your SuggestionBox is for example the last thing in a page, the suggestions are hidden (go under the text box and out of the screen/under the keyboard).

**Comment by dotMorten** [comment]
Should be doable by using the constraints here to move it in a different place:
https://github.com/dotMorten/XamarinFormsControls/blob/184b72038c2c127a64bd548b42e8f6ee442c4975/AutoSuggestBox/NativeAutoSuggestBox.iOS.cs#L140-L142

**Comment by FedericoJoseLucia** [comment]
Im currently having this issue in Android. The keyboard is covering the suggestions. Any idea how can I fix it?

**Comment by dotMorten** [comment]
@FedericoJoseLucia This is about iOS flowing the suggestion box in opposite direction and different from what you're experiencing. Please open a separate issue _with_ a sample that reproduces the issue.
