### ISSUE TITLE
UWP release build doesn't work - no edit box

### ISSUE THREAD

**Issue by marksn-ms** [dotMorten/XamarinFormsControls#38]
### Description
When the sample application is built in release mode for UWP, no edit box is displayed making the control unusable.  It works fine in debug mode for UWP.  It also works fine for Android in both release and debug modes.  Didn't test iOS yet.

### Steps to Reproduce

1. Clone repo
2. Open solution
3. Change configuration to Release - x86 - SampleApp.UWP (Universal Windows)
4. Build and run

### Expected Behavior
The sample app should behave the same as the debug mode build.

### Actual Behavior
There are no edit boxes for text entry.

### Basic Information

- Version with issue:  Latest version in GitHub.
- Last known good version:  Unknown
- IDE:  VS2017
- Platform Target Frameworks:
  - iOS:  untested
  - Android: works fine in both debug and release 
  - UWP:  16299

**Comment by jgilmorekim** [comment]
I am also seeing this issue, please help.

**Comment by dotMorten** [comment]
Make sure you add the following to Xamarin.Forms init in your app, so the optimizer doesn't get rid of it:
```cs
List<Assembly> assembliesToInclude = new List<Assembly>();
assembliesToInclude.Add(typeof(dotMorten.Xamarin.Forms.AutoSuggestBox).GetTypeInfo().Assembly);
Xamarin.Forms.Forms.Init(e, assembliesToInclude);
```
I'll get that added to the sample app too (sorry I forgot)
