### ISSUE TITLE
suggested text got cut

### ISSUE THREAD

**Issue by Sevensakura** [dotMorten/XamarinFormsControls#42]
### Description
hello dotMorten, i am having an issue with suggested text, it cut off at the end of line if line are too long.
the issue are pretty much same with android and Ios. can you help me?
thank you very much and sorry for any inconvenient 

iOS: Ios 9 >
Android: 8.1

### Screenshots
![test](https://user-images.githubusercontent.com/49476997/56110173-bb556f80-5f7d-11e9-8b59-1ffc19795dc8.jpg)

**Comment by dotMorten** [comment]
What would you expect to be happening here? I can't just magically make your screen wider.

I'm not really sure auto-completion on very large texts makes that much sense either, and I'd be really worried what line-breaking large texts would look like.

More importantly it matches the behavior of UWP's AutoSuggestBox, which this control is meant to be a cross-platform port of:
![image](https://user-images.githubusercontent.com/1378165/56162392-c1008480-5f80-11e9-8248-5626aa21fe23.png)

**Comment by Sevensakura** [comment]
hi dotMorten, i am sorry i haven't mention it yet.
maybe if possible, an horizontal scrollbar maybe?

i am working on some data that need auto completion and some of them got long line on text.
so maybe horizontal scrollbar can be good. 
thank you very much

**Comment by hungthe50** [comment]
Hi dotMorten, You can design the list suggest like a scroll view with height limit instead of being stretched across the sreen? Because I use control in my project suggest on search bar of maps. Thank you verry much

**Comment by dotMorten** [comment]
Could you share a screenshot of the look and feel you're looking to do?
I'm not sure I can do anything but text here either.

**Comment by Sevensakura** [comment]
hi dotMorten, can you add font size attribute on suggest box? 
it will help me. thank you very much

**Comment by dotMorten** [comment]
@Sevensakura Please see issue #2, and also yet again, please don't post comments unrelated to the issue you're posting in (look for an existing issues and if you don't find any that matches, open a new issue).

**Comment by hungthe50** [comment]
![image](https://user-images.githubusercontent.com/33857051/57912148-c9b3e580-78b3-11e9-89f1-eedea1ec7925.png)

The suggested list spreads out the screen while I just want it to show about 5 lines, @dotMorten

**Comment by hungthe50** [comment]
I want The suggested list height about 5 lines like the one I highlighted on the image
![image](https://user-images.githubusercontent.com/33857051/57912611-edc3f680-78b4-11e9-9edb-0f6caaeea50f.png)

**Comment by dotMorten** [comment]
@hungbe50 please log a relevant issue for this instead of hijacking this unrelated thread

**Comment by dotMorten** [comment]
Closing due to no response.
