### ISSUE TITLE
There is no way to set the selected item programmatically

### ISSUE THREAD

**Issue by maximedubois** [dotMorten/XamarinFormsControls#44]
There's no way to set on page load the selected item. I'm currently storing the selected item value on local storage of the device and when the user comes back to that page where I have the autosuggestbox I want to prefill it with the selected value. How can it be achieved?

**Comment by dotMorten** [comment]
@maximedubois This isn't a list to select from. This is a control to help you auto-complete a text string. You'd be setting the Text property instead.
