### ISSUE TITLE
Suggestion box width and Multiple column

### ISSUE THREAD

**Issue by gutierrezralph** [dotMorten/XamarinFormsControls#47]
Is it possible to make a suggestion box wider than the text box?

Ex.
Textbox width set to 100
the suggestion flyout box can be set to 300 or wider if needed

and also how can we set the suggestion flyout box to multiple columns?
![image](https://user-images.githubusercontent.com/26339824/57973275-0c231280-79d9-11e9-8083-87ea77f1c445.png)

**Comment by dotMorten** [comment]
There's currently no ability to control the flyout width or adding more columns. The control wraps native controls and they wouldn't all provide that support, so I don't think I could pull this off with the native controls.
