### ISSUE TITLE
Cannot set SuggestionBox Text in Code-Behind

### ISSUE THREAD

**Issue by siameseSerpent** [dotMorten/XamarinFormsControls#5]
When I attempt to set the text property in the code behind via <objectname>.Text = "stringhere" the TextChanged event is thrown 3 times. For the first 2 times it is thrown, the Text is set properly. However, when it is thrown the third time and the new page actually renders with the SuggestionBox, the Text of the SuggestionBox is not set and instead simply shows the PlaceholderText.

Thanks

**Comment by dotMorten** [comment]
@siameseSerpent Thanks. Which platform are you seeing this on?

**Comment by siameseSerpent** [comment]
@dotMorten It seems to be both.
Steps to reproduce bug with setting text in xaml:
1. Create new Xamarin Forms Android XAML Project in Visual Studio
2. Create autosuggestbox on MainPage.xaml
3. Assign a Text value in the xaml Text="textHere"
4.Assign an ItemsSource of a small list of strings in the MainPage.xaml.cs
5. The autosuggestbox will appear and will filter the list of string properly but will not populate initially with the text from the xaml property (see below).
https://puu.sh/ARZOd/9f5cf755c4.png MainPage.xaml.cs
https://puu.sh/ARZOs/49df33e3fd.png MainPage.xaml
https://puu.sh/ARZOS/baa52a4062.png App running on test S8+

For setting the text in the code-behind, the reproduction steps are similar, except you do not set the text in the xaml and instead do suggestBox.Text = "TextHere" as seen below.
https://puu.sh/ARZQR/071c73e451.png MainPage.xaml.cs
https://puu.sh/ARZR8/4790f9c4ee.png MainPage.xaml
https://puu.sh/ARZRk/6a580873c2.png App running on test S8+

Both of these tests were performed on a clean project.

Thanks

**Comment by dotMorten** [comment]
I'm a little confused. The fix you submitted fixes the setter (thanks for that!) but it doesn't explain the multiple text-changed event you describe above? Or am I missing something and it does indeed also fix that?

**Comment by siameseSerpent** [comment]
@dotMorten I am also confused, as I did not submit a fix. When I attempt to set the text that is supposed to appear in the AutoSuggestBox, whether I attempt to set it from the xaml Text property or in the code-behind, the text will not set properly and it will not appear in the app. The multiple text-changed events is simply a suggestion as to what might be causing the problem; when I open a new NavigationPage with only an AutoSuggestBox in Xamarin.Forms, the AutoSuggestBox throws 3 TextChanged events for seemingly no reason. When I try to set the text, it will seemingly set according to Visual Studio, but then it empties the Text property on the third event call. I have not solved a problem and still have found a way to manually set the text which appears in the AutoSuggestBox in the app.

If you require any more documentation or further clarification, please feel free to @ me.

Thanks
