### ISSUE TITLE
Not able to run the project

### ISSUE THREAD

**Issue by SagarPanwala** [dotMorten/XamarinFormsControls#51]
### Description
Below is the build output.

Target CoreCompile:
CSC : error CS0006: Metadata file '/Users/sagarpanwala/Downloads/XamarinFormsControls-master/AutoSuggestBox/bin/Debug/xamarinios10/dotMorten.Xamarin.Forms.AutoSuggestBox.dll' could not be found
CSC : error CS0006: Metadata file '/Users/sagarpanwala/Downloads/XamarinFormsControls-master/SampleApp/SampleApp/bin/Debug/xamarinios10/SampleApp.dll' could not be found
Done building target "CoreCompile" in project "SampleApp.iOS.csproj" -- FAILED.

Done building project "SampleApp.iOS.csproj" -- FAILED.

Build FAILED.

CSC : error CS0006: Metadata file '/Users/sagarpanwala/Downloads/XamarinFormsControls-master/AutoSuggestBox/bin/Debug/xamarinios10/dotMorten.Xamarin.Forms.AutoSuggestBox.dll' could not be found
CSC : error CS0006: Metadata file '/Users/sagarpanwala/Downloads/XamarinFormsControls-master/SampleApp/SampleApp/bin/Debug/xamarinios10/SampleApp.dll' could not be found
0 Warning(s)
2 Error(s)

I tried to run Android and iOS project and I'm running on Mac machine.

**Comment by dotMorten** [comment]
This project needs to be built on Windows, or from commandline using msbuild (VS4Mac doesn't support multi-targeting yet)
