### ISSUE TITLE
AutoSuggestionBox not working on iOS with Rg.Popup page 

### ISSUE THREAD

**Issue by sahadevgupta** [dotMorten/XamarinFormsControls#6]
I'm using this autosuggestion on a popup page but the suggestion list is not visible. I've checked data is been properly passed tableViewSource has proper list count but the suggestion list is not visible. This problem occurs only on Popup page.

**Comment by sahadevgupta** [comment]
![Uploading Screenshot (12).png…]()

**Comment by dotMorten** [comment]
What are the repro steps?

**Comment by sahadevgupta** [comment]
I've a button on a page and when I clicked that button popup page is visible . On that popup page i was trying to use autosuggestion box but it wasn't being able to use it.

**Comment by dotMorten** [comment]
Sorry as much I would like to help you, I need much more help from you with setting up a sample app the shows the problem. I have no way to recreate the issue you're experiencing as you have provided no detail or preferably a simple app that  demonstrates the problem. Not a single line of code showing what you're doing.
Read the above and ask yourself if someone else gave you the description you gave me, would you have enough information to verify the bug and start working on a fix.

**Comment by sahadevgupta** [comment]
Sample Project:

https://drive.google.com/file/d/1V_luI00LlblXAxBzWUcibTWntFVB5lo_/view?usp=sharing

**Comment by sahadevgupta** [comment]
Steps to reproduce error:
1. Run app on iOS
2. Click Button on a home screen, 
3. popup page will appear which has autosuggestion box
4. When you try to enter text it gives error out message.

Same thing is working on Android and UWP.

**Comment by AbuMandour** [comment]
i have the same issue, any help?

**Comment by dotMorten** [comment]
Adding repro sample provided by @sahadevgupta here: [AutoSuggestBox.zip](https://github.com/dotMorten/XamarinFormsControls/files/2751713/AutoSuggestBox.zip)

**Comment by dotMorten** [comment]
@sahadevgupta @AbuMandour Thank you for the great reproducer, and sorry for the slow response. I just pushed a fix.
