### ISSUE TITLE
Not able to get text value when trying to implement Prism behaviours

### ISSUE THREAD

**Issue by devoirtechsandip** [dotMorten/XamarinFormsControls#7]
Hi,

I am able to get text value.

XAML : 
```xml
<autoforms:AutoSuggestBox PlaceholderText="Search" 
        ItemsSource="{Binding ItemList}"
        BackgroundColor="Black">
   <autoforms:AutoSuggestBox.Behaviors>
          <b:EventToCommandBehavior EventName="TextChanged" Command="{Binding TextChangedCommand}" EventArgsConverter="{converters:AutoSuggestBoxTextChangedEventArgsConverter}"/>
   </autoforms:AutoSuggestBox.Behaviors>         
</autoforms:AutoSuggestBox>
 ```       

ViewModel : 
```cs
private DelegateCommand<AutoSuggestBoxTextChangedEventArgs> _TextChangedCommand;
public DelegateCommand<AutoSuggestBoxTextChangedEventArgs> TextChangedCommand => _TextChangedCommand ?? (_TextChangedCommand = new DelegateCommand<AutoSuggestBoxTextChangedEventArgs>(TextChangedFunction));

private void TextChangedFunction(AutoSuggestBoxTextChangedEventArgs selectedItem)
{
	//var item = selectedItem.Reason.ToString();
	if (selectedItem.Reason == AutoSuggestionBoxTextChangeReason.UserInput)
	{
		if (string.IsNullOrWhiteSpace(UserText) || UserText.Length < 3)
		{ }
		//box.ItemsSource = null;
		else
		{
			//var suggestions = await GetSuggestions(box.Text);
			//box.ItemsSource = suggestions.ToList();
		}
	}
}
```
behaviors implementation : 
```cs
public class AutoSuggestBoxTextChangedEventArgsConverter : IValueConverter
{
	public object Convert(object value, Type targetType, object parameter, CultureInfo culture)
	{
		var itemTappedEventArgs = value as AutoSuggestBoxTextChangedEventArgs;
		if (itemTappedEventArgs == null)
		{
			throw new ArgumentException("Expected value to be of type ItemTappedEventArgs", nameof(value));
		}
		var item = itemTappedEventArgs.Reason;
		return item;
	}

	public object ConvertBack(object value, Type targetType, object parameter, CultureInfo culture) => null;
} 
```

**Comment by dotMorten** [comment]
When you say you're unable to get the text, where is it in that code that's a problem?

**Comment by dotMorten** [comment]
Also in your VM you access a variable `UserText` but I don't see that declared anywhere. Do you have a sample project that compiles you can share, and that throws an exception where the issue you're having occurs, so I can debug that?

**Comment by devoirtechsandip** [comment]
This is code snippet given in Sample.

 private async void dynamicSuggestBox_TextChanged(object sender, dotMorten.Xamarin.Forms.AutoSuggestBoxTextChangedEventArgs args)
        {
            AutoSuggestBox box = (AutoSuggestBox)sender;
            // Only get results when it was a user typing, 
            // otherwise assume the value got filled in by TextMemberPath 
            // or the handler for SuggestionChosen.
            if (args.Reason == AutoSuggestionBoxTextChangeReason.UserInput)
            {
                if (string.IsNullOrWhiteSpace(box.Text) || box.Text.Length < 3)
                    box.ItemsSource = null;
                else
                {
                    var suggestions = await GetSuggestions(box.Text);
                    box.ItemsSource = suggestions.ToList();
                }
            }
        }

I am successfully able to implement prism behaviors for "AutoSuggestBoxTextChangedEventArgs" where in I am able to get the "AutoSuggestionBoxTextChangeReason". But as in sample code you are using "AutoSuggestBox box = (AutoSuggestBox)sender;" to get the current textvalue which is where I am facing issue.

How to get Text value of user input, when response is sent from converter.

**Comment by devoirtechsandip** [comment]
Hi, how to pass input text and input method to view model from converter

**Comment by MarcosCobena** [comment]
Hi,

I've been playing for a few days with this control as per the last stable version from NuGet I've found no way to rely just in commands to handle everything from the VM:
- because I stumble upon Text being rewritten if I set an initial value (it's marked as TwoWay explicitly); or
- leveraging the 3 recommended events to commands let me no way to pass Text, which's happening you @devoirtechsandip too

I think will shift everything to code-behind for now.

**Comment by brianlagunas** [comment]
If I understand correctly, you are trying to access the control instance inside of a converter? Why not just pass the control as the EventArgsConverterParameetr and use it in your converter?  Also, your DelegateCommand is using the wrong type. You aren't using the `AutoSuggestBoxTextChangedEventArgs` in the VM, you are passing a different object type. You'll need to change that too.

**Comment by dotMorten** [comment]
Thanks @brianlagunas ! Closing, but feel free to re-open if Brian's suggestion isn't sufficient.
