### ISSUE TITLE
Set Multiple Display Paths

### ISSUE THREAD

**Issue by FedericoJoseLucia** [dotMorten/XamarinFormsControls#73]
Hi, would it be possible to add multiple Display Member Paths? Maybe separated by a dash. I was looking at "FormatType" method and thought it could take some sort of list by parameter.

Any case, great work. Hope some day be able to contribute.

**Comment by dotMorten** [comment]
No there isn't. Typically that would be done with an item template but that's not possible with native controls.
Instead create a field in your view model like "DisplayName" or something and have that property format how you want it.
